/** 포트폴리오 데모용 스터디 100건 — 제목·닉네임·소개 조합 */

const BACKGROUNDS = [
  'green',
  'yellow',
  'blue',
  'pink',
  'mouse_tablet',
  'tablet_bottle',
  'diamond',
  'leaf',
];

const EMOJI_POOL = [
  { code: '1F525', count: 12 },
  { code: '1F4AA', count: 8 },
  { code: '1F680', count: 15 },
  { code: '1F4DA', count: 6 },
  { code: '1F60A', count: 20 },
  { code: '1F602', count: 4 },
  { code: '2728', count: 9 },
  { code: '1F389', count: 7 },
];

const STUDIES = [
  { nickname: '코딩하는민수', name: '알고리즘 1일 1문제', intro: '백준 실버부터 같이 올라가요. 틀려도 괜찮아요!' },
  { nickname: '밤샘조', name: 'React hooks 정복하기', intro: 'useEffect 지옥에서 탈출하는 게 목표입니다.' },
  { nickname: '열공러지니', name: 'CS 기본기 스터디', intro: 'OS·네트워크·DB를 면접 전까지 한 바퀴!' },
  { nickname: '아침형인간', name: '매일 6시 기상 챌린지', intro: '일찍 일어나서 30분 코딩하기. 주말은 8시 OK.' },
  { nickname: '토익맨', name: '토익 900 목표반', intro: 'RC/LC 번갈아 풀고 오답 공유해요.' },
  { nickname: '독서광', name: 'IT 책 한 달 1권', intro: '이번 달은 클린 코드! 끝나면 요약 공유.' },
  { nickname: '포트폴리오준비생', name: 'Next.js 사이드 프로젝트', intro: '주 3회 온라인 스탠드업 후 각자 PR 올리기.' },
  { nickname: 'SQL덕후', name: 'SQLD 합격 스터디', intro: '기출 위주로 풀고 틀린 유형만 모아요.' },
  { nickname: '디자인입문', name: 'Figma UI 연습', intro: '랜딩페이지 1장씩 클론 코딩해봅니다.' },
  { nickname: '취준생A', name: '자기소개서 첨삭 모임', intro: '서로 피드백 주고 2주마다 버전 업!' },
  { nickname: '영어회화초보', name: '영어 스피킹 10분', intro: '매일 짧은 주제로 말하기. 부담 NO.' },
  { nickname: '운동겸공부', name: '헬스 후 공부 1시간', intro: '운동 인증하고 바로 책상 앞으로!' },
  { nickname: 'JS마스터', name: 'JavaScript 심화', intro: '클로저, 프로토타입, 이벤트루프 끝까지 파기.' },
  { nickname: 'Spring입문', name: 'Spring Boot REST API', intro: 'CRUD부터 JWT까지 차근차근.' },
  { nickname: 'Python러버', name: '파이썬 자동화 스터디', intro: '엑셀·크롤링·간단 봇 만들어봐요.' },
  { nickname: '면접준비중', name: '기술 면접 질문 리스트', intro: '하루 5개씩 답변 정리하고 모의면접.' },
  { nickname: '블로그작가', name: 'TIL 블로그 챌린지', intro: '공부한 내용 매일 짧게라도 글 남기기!' },
  { nickname: '노마드꿈', name: '원격 근무 준비반', intro: '영어+포트폴리오+GitHub 꾸준히.' },
  { nickname: '강남러닝', name: '정보처리기사 실기', intro: '기출 3회독이 목표. 같이 풀어요!' },
  { nickname: '카페공부러', name: '카공 2시간 인증', intro: '사진 찍고 집중 시간 공유하는 소소한 습관.' },
  { nickname: '프론트지망', name: 'CSS Grid·Flex 완전정복', intro: '레이아웃 막히면 스크린샷 올려주세요.' },
  { nickname: '백엔드지망', name: 'Express + Prisma 실습', intro: 'REST API 만들고 Swagger까지!' },
  { nickname: '데이터분석', name: 'Pandas 입문', intro: '공공데이터로 간단 분석 프로젝트.' },
  { nickname: '게임만들기', name: 'Unity 2D 입문', intro: '주말에 2시간씩 플랫포머 만들기.' },
  { nickname: '모바일앱', name: 'React Native 토이앱', intro: '할 일 앱 하나 완성이 1차 목표.' },
  { nickname: 'DevOps관심', name: 'Docker 기초', intro: '컨테이너 띄우고 배포까지 따라하기.' },
  { nickname: 'Git헷갈림', name: 'Git 브랜치 전략', intro: 'rebase vs merge 실습 위주로!' },
  { nickname: '타입스크립트', name: 'TS 마이그레이션', intro: 'JS 프로젝트에 TS 점진 적용해봐요.' },
  { nickname: '알고리즘초보', name: '코딩테스트 입문', intro: '프로그래머스 Lv.0~1부터 천천히.' },
  { nickname: '수학공포', name: '개발자를 위한 수학', intro: '선형대수·확률 가볍게 복습.' },
  { nickname: 'UX관심', name: '사용성 테스트 연습', intro: '서로 사이트 써보고 개선점 적기.' },
  { nickname: '스터디장연습', name: '스터디 운영법 공유', intro: '진행·회고 방법 나누는 메타 스터디.' },
  { nickname: '코테불합격', name: 'DFS/BFS 집중반', intro: '그래프 문제만 2주간 몰아치기!' },
  { nickname: '일본어공부', name: 'JLPT N3 준비', intro: '단어 20개 + 문법 1개씩.' },
  { nickname: '중국어초보', name: 'HSK 3급', intro: '발음 같이 연습해요.' },
  { nickname: '발표연습', name: '프로젝트 발표 리허설', intro: '5분 발표 + Q&A 받기.' },
  { nickname: '코드리뷰', name: 'PR 코드리뷰 연습', intro: '서로 PR 올리고 코멘트 달기.' },
  { nickname: '테스트코드', name: 'Jest 단위테스트', intro: '커버리지 50% 목표까지!' },
  { nickname: '성능최적화', name: '웹 성능 튜닝', intro: 'Lighthouse 점수 올리기 챌린지.' },
  { nickname: '접근성', name: 'a11y 기본', intro: '키보드·스크린리더 관점으로 UI 점검.' },
  { nickname: 'Redis공부', name: '캐시 전략 입문', intro: 'Redis로 세션·캐시 실습.' },
  { nickname: 'Kafka관심', name: '메시지 큐 개념', intro: '이벤트 기반 아키텍처 가볍게.' },
  { nickname: 'AWS입문', name: 'EC2·S3 핸즈온', intro: '프리티어로 배포 한번 해봅시다.' },
  { nickname: '클라우드자격', name: 'AWS SAA 준비', intro: '강의 1강씩 + 기출.' },
  { nickname: 'Linux초보', name: '리눅스 명령어', intro: 'vim·grep·chmod 익숙해지기.' },
  { nickname: '네트워크공부', name: 'HTTP 완전정복', intro: 'REST·쿠키·CORS 정리.' },
  { nickname: '보안관심', name: 'OWASP Top 10', intro: '취약점 사례 읽고 방어 방법.' },
  { nickname: '블록체인궁금', name: 'Web3 입문', intro: '지갑·스마트컨트랙트 개념만.' },
  { nickname: 'AI활용', name: 'ChatGPT로 코딩하기', intro: '프롬프트 잘 쓰는 법 공유.' },
  { nickname: 'ML입문', name: '머신러닝 기초', intro: 'scikit-learn 튜토리얼 따라하기.' },
  { nickname: '이력서첨삭', name: '이력서·포트폴리오', intro: '2주마다 버전 공유하고 피드백.' },
  { nickname: 'LinkedIn', name: 'LinkedIn 프로필', intro: '영문 프로필 다듬기.' },
  { nickname: '스크럼연습', name: '애자일 스크럼', intro: '데일리 15분 + 스프린트 회고.' },
  { nickname: '기획자지망', name: '와이어프레임', intro: 'Figma로 화면 흐름 그리기.' },
  { nickname: 'PM관심', name: 'PRD 작성 연습', intro: '기능 명세서 1페이지씩.' },
  { nickname: '스타트업', name: '아이디어 피칭', intro: '1분 피치 연습하고 피드백.' },
  { nickname: '사이드hustle', name: '부수입 프로젝트', intro: '소규모 SaaS 아이디어 검증.' },
  { nickname: '오픈소스', name: 'OSS 기여 입문', intro: 'good first issue 찾아서 PR.' },
  { nickname: '해커톤준비', name: '해커톤 팀 빌딩', intro: '아이디어·역할 나누기.' },
  { nickname: '대학생1', name: '전공 과제 스터디', intro: '자료구조 과제 같이 풀어요.' },
  { nickname: '대학생2', name: '졸업프로젝트', intro: '주 2회 진행상황 공유.' },
  { nickname: '부트캠프생', name: '코드잇 10기 복습', intro: '프로젝트 전 배운 거 정리.' },
  { nickname: '커리어전환', name: '비전공 개발 입문', intro: '기초부터 천천히, 서로 응원!' },
  { nickname: '40대도전', name: '늦깎이 개발자', intro: '나이 상관없이 꾸준히.' },
  { nickname: '주말코더', name: '주말 4시간 코딩', intro: '평일은 바쁘니 주말만!' },
  { nickname: '출퇴근러', name: '출근길 팟캐스트', intro: '개발 팟캐스트 듣고 메모 공유.' },
  { nickname: '육아맘', name: '육아와 공부', intro: '아이 잠든 후 1시간만!' },
  { nickname: '군휴가', name: '전역 후 취업 준비', intro: '휴가 때 집중 스프린트.' },
  { nickname: '프리랜서', name: '외주 견적·계약', intro: '실무 팁 나누기.' },
  { nickname: '노션정리', name: 'Notion 위키 만들기', intro: '공부 노트 템플릿 공유.' },
  { nickname: '옵시디언', name: 'Obsidian PKM', intro: '링크로 지식 연결하기.' },
  { nickname: '마크다운', name: 'README 잘 쓰기', intro: '포트폴리오 문서화 연습.' },
  { nickname: 'Swagger', name: 'API 문서화', intro: 'OpenAPI 스펙 작성 연습.' },
  { nickname: 'E2E테스트', name: 'Playwright 입문', intro: '핵심 플로우 1개 자동화.' },
  { nickname: 'CI/CD', name: 'GitHub Actions', intro: 'lint·test·deploy 파이프라인.' },
  { nickname: '모노레포', name: 'Turborepo 실습', intro: 'FE+BE 같이 관리하기.' },
  { nickname: 'GraphQL', name: 'GraphQL 입문', intro: 'REST와 비교하며 학습.' },
  { nickname: 'WebSocket', name: '실시간 채팅', intro: 'Socket.io 토이 프로젝트.' },
  { nickname: 'Three.js', name: '3D 웹 입문', intro: '간단한 3D 씬 만들기.' },
  { nickname: 'Canvas', name: '캔버스 API', intro: '미니 게임 하나 만들어봐요.' },
  { nickname: 'PWA', name: 'PWA 만들기', intro: '오프라인·설치 가능한 웹앱.' },
  { nickname: 'SEO', name: 'SEO 기본', intro: '메타태그·sitemap 정리.' },
  { nickname: 'i18n', name: '다국어 지원', intro: 'react-i18next 적용해보기.' },
  { nickname: '상태관리', name: 'Zustand vs Redux', intro: '작은 앱으로 비교 실습.' },
  { nickname: 'Recoil', name: 'Recoil 실험', intro: 'atom·selector 익히기.' },
  { nickname: 'TanStack', name: 'React Query', intro: '서버 상태 관리 패턴.' },
  { nickname: 'Storybook', name: '컴포넌트 문서화', intro: 'UI 컴포넌트 카탈로그.' },
  { nickname: 'Tailwind', name: 'Tailwind CSS', intro: 'utility-first로 빠르게 UI.' },
  { nickname: 'Styled', name: 'styled-components', intro: 'CSS-in-JS 스타일링.' },
  { nickname: 'Sass', name: 'SCSS 리팩터링', intro: 'BEM·mixin 정리.' },
  { nickname: 'Webpack', name: '번들러 이해', intro: 'Vite·Webpack 차이 정리.' },
  { nickname: 'Node심화', name: 'Node.js 이벤트루프', intro: '비동기 패턴 deep dive.' },
  { nickname: 'NestJS', name: 'NestJS 입문', intro: '모듈·DI·데코레이터.' },
  { nickname: 'FastAPI', name: 'FastAPI REST', intro: 'Python 백엔드 빠르게.' },
  { nickname: 'Go언어', name: 'Go 기초 문법', intro: 'goroutine 맛보기.' },
  { nickname: 'Rust관심', name: 'Rust ownership', intro: 'The Book 1~3장.' },
  { nickname: 'Kotlin', name: 'Kotlin Android', intro: '간단한 앱 하나.' },
  { nickname: 'Swift', name: 'SwiftUI 입문', intro: 'iOS 토이앱.' },
  { nickname: 'Flutter', name: 'Flutter 크로스', intro: '한 codebase로 iOS+Android.' },
  { nickname: '면접스터디', name: 'CS 면접 100선', intro: '하루 3개 질문·답변.' },
  { nickname: '라이브코딩', name: '화이트보드 연습', intro: 'Zoom 켜고 30분씩.' },
  { nickname: '페어프로그래밍', name: '페어 코딩', intro: 'driver/navigator 번갈아.' },
  { nickname: '코드골프', name: '짧은 코드 챌린지', intro: '재미로 한 줄 줄이기.' },
  { nickname: '레트로', name: '스프린트 회고', intro: 'KPT 회고 템플릿.' },
  { nickname: '독서모임', name: '개발 서적 2주 1권', intro: '이번엔 리팩터링 2판!' },
  { nickname: '영화토론', name: 'IT 다큐 시청', intro: '실리콘밸리 등 보고 토론.' },
  { nickname: '컨퍼런스', name: '발표 영상 정리', intro: 'FEConf·JSConf 요약 공유.' },
  { nickname: '네트워킹', name: '개발자 모임', intro: '온라인 커피챗 연습.' },
  { nickname: '멘토링', name: '주니어 멘토링', intro: '선배·후배 경험 나누기.' },
  { nickname: '번아웃', name: '번아웃 예방', intro: '쉬는 날도 인정하기.' },
  { nickname: '건강', name: '거북목 스트레칭', intro: '25분마다 스트레칭 알림.' },
  { nickname: '명상', name: '5분 명상', intro: '공부 전 마음 가다듬기.' },
  { nickname: '시간관리', name: '뽀모도로 4세트', intro: '25+5 집중 사이클.' },
  { nickname: '목표설정', name: 'OKR 개인版', intro: '분기 목표 세우고 체크.' },
  { nickname: '습관형성', name: '66일 챌린지', intro: '작은 습관 하나 고정.' },
  { nickname: '감사일기', name: '오늘의 감사 1줄', intro: '긍정 마인드 유지.' },
  { nickname: '코딩테스트2', name: '프로그래머스 Lv.2', intro: '이분탐색·투포인터.' },
  { nickname: '백준실버', name: '백준 실버 50제', intro: '유형별 5문제씩.' },
  { nickname: 'LeetCode', name: 'LeetCode Easy', intro: '영문 문제 읽기 연습.' },
  { nickname: '코딩캠프', name: '여름방학 집중', intro: '8월 한 달 몰입!' },
  { nickname: '겨울방학', name: '방학 프로젝트', intro: '2주 안에 MVP.' },
  { nickname: '팀프로젝트', name: '6인 팀 협업', intro: 'Git flow·PR 규칙 정하기.' },
  { nickname: '코드잇졸업', name: '수료 후 취업', intro: '이력서·면접 같이 준비.' },
  { nickname: '공부의숲', name: '공부의 숲 베타테스터', intro: '기능 써보고 피드백 주세요!' },
  { nickname: '데모계정', name: '채용담당자님 환영', intro: '비밀번호 qwert12345! 로 모든 스터디 열람 가능해요.' },
];

export function getSeedStudies() {
  if (STUDIES.length < 100) {
    throw new Error(`seed-data: ${STUDIES.length} entries, need 100`);
  }
  return STUDIES.slice(0, 100).map((study, index) => ({
    ...study,
    image: BACKGROUNDS[index % BACKGROUNDS.length],
    daysAgo: (index * 3) % 120,
    points: Math.floor((index * 47 + 13) % 480) + 10,
  }));
}

export const DEMO_PASSWORD = 'qwert12345!';
